//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratory.Data.BaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analyzes
    {
        public int Id { get; set; }
        public int RequestServicesId { get; set; }
        public System.DateTime DateCompletion { get; set; }
        public string Result { get; set; }
    
        public virtual RequestServices RequestServices { get; set; }
    }
}
