//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratory.Data.BaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalLaboratoryEntities : DbContext
    {
        private static MedicalLaboratoryEntities context;
        public static MedicalLaboratoryEntities getContext()
        {
            if (context == null)
                context = new MedicalLaboratoryEntities();
            return context;
        }
        public MedicalLaboratoryEntities()
            : base("name=MedicalLaboratoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analyzes> Analyzes { get; set; }
        public virtual DbSet<AuthorizationHistory> AuthorizationHistory { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<RequestServices> RequestServices { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<RequestWithServices> RequestWithServices { get; set; }
    }
}
