//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratory.Data.BaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestServices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestServices()
        {
            this.Analyzes = new HashSet<Analyzes>();
        }
    
        public int Id { get; set; }
        public int RequestId { get; set; }
        public int ServiceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Analyzes> Analyzes { get; set; }
        public virtual Request Request { get; set; }
        public virtual Service Service { get; set; }
    }
}
