//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratory.Data.BaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestWithServices
    {
        public int Id { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public string ClientInfo { get; set; }
        public string UserInfo { get; set; }
        public string Services { get; set; }
        public Nullable<decimal> Summ { get; set; }
    }
}
